tankS3FileCreatedHandler:
  handler: handlers/tankS3FileCreatedHandler.process
  timeout: 900

  events:
    - s3:
        bucket: commandeer-tanks
        event: s3:ObjectCreated:*
        existing: true
        rules:
          - suffix: .json
