hotStockHandler:
  handler: handlers/hotStock/hotStockHandler.process
  events:
    - http:
        path: great-deals
        # cors: ${file(handlers/_base/cors.yml):cors}
        method: get
  environment:
    VERBOSE: false
