- name: Create the S3 Tanks bucket
  s3_bucket:
    name: commandeer-tank
    versioning: yes
    tags:
      name: Tanks
      type: demo

- name: Upload tank A1 configuration
  aws_s3:
    bucket: commandeer-tank
    object: tanks/a1.json
    src: "./a1.json"
    mode: put

- name: Create a hangar folder for tanks
  aws_s3:
    bucket: commandeer-tank
    object: tanks/hangar
    mode: create
